# Generated by Django 2.2.17 on 2020-12-14 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='drrtare',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='hgjg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_hgjg', to='home.CustomText'),
        ),
        migrations.AddField(
            model_name='customtext',
            name='jhgjgjg',
            field=models.ManyToManyField(blank=True, related_name='customtext_jhgjgjg', to=settings.AUTH_USER_MODEL),
        ),
    ]
