# Generated by Django 2.2.17 on 2020-12-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201214_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hgjg',
        ),
    ]
